---
lang: en
title: "Some example slides"
subtitle: "A slide deck with various examples"
author: Jeremy Fix
duration: 90
theme: white
css: 
- custom.css
width: 1600
height: 1000
margin: 0.
center: false
embedded: false
hideAddressBar: true
rtl: false                 # Right to left or Left to Right
slideNumber: true  
rollingLinks: true         # Does not work
showNotes: false
fragments: true
transition: none
touch: true
keywords:
- example deck
- reveal.js 
- pandoc
---

